# Default values for demo-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nginx:
  name: nginx
  image:
    name: app-nginx
    tag: v2
    exposedPort: 80
  
  replicas: 1

  service:
    type: Nodeport